package com.xwal.domain.model

import org.junit.jupiter.api.Test
import java.time.Instant
import kotlin.test.*

/**
 * Tests data class generated methods (copy, equals, hashCode, toString, componentN)
 * to cover Kotlin-generated bytecode that JaCoCo measures.
 */
class DataClassCoverageTest {

    private val now = Instant.now()

    @Test fun `Workflow copy and equals`() {
        val w = Workflow(WorkflowId.generate(), "a", "1", "d", IwmDefinition("{\"workflow\":{}}"), WorkflowStatus.ACTIVE, now, "u", now, null)
        val copy = w.copy(name = "b")
        assertEquals("b", copy.name)
        assertNotEquals(w, copy)
        assertEquals(w, w.copy())
    }

    @Test fun `Workflow toString contains name`() { assertTrue(Workflow(WorkflowId.generate(), "myWf", "1", null, IwmDefinition("{}"), WorkflowStatus.DRAFT, now, null, now, null).toString().contains("myWf")) }

    @Test fun `WorkflowInstance copy`() {
        val i = WorkflowInstance(InstanceId.generate(), WorkflowId.generate(), "e1", EngineAdapterId.generate(), InstanceStatus.RUNNING, "BK", mapOf("x" to 1), now, "u", null, now, now)
        assertEquals(InstanceStatus.COMPLETED, i.copy(status = InstanceStatus.COMPLETED).status)
        assertNotNull(i.toString())
        assertNotNull(i.hashCode())
    }

    @Test fun `EngineAdapterConfig endpointUrl`() {
        val c = EngineAdapterConfig(EngineAdapterId.generate(), "n", EngineType.CAMUNDA7, mapOf("url" to "http://x"), null, true, HealthStatus.HEALTHY, now, 0, now, null, now, null)
        assertEquals("http://x", c.endpointUrl)
        val noUrl = c.copy(config = emptyMap())
        assertNull(noUrl.endpointUrl)
    }

    @Test fun `EngineAdapterConfig toString`() {
        val c = EngineAdapterConfig(EngineAdapterId.generate(), "test", EngineType.FLOWABLE, mapOf("url" to "http://localhost"), AdapterCapabilities.createBpmnCapabilities(), false, HealthStatus.UNHEALTHY, now, 5, now, "admin", now, "editor")
        assertNotNull(c.toString())
        assertEquals("test", c.name)
        assertEquals(false, c.enabled)
    }

    @Test fun `Task copy and fields`() {
        val t = Task(TaskId.of(EngineType.CAMUNDA7, "t1"), "name", "type", "desc", "alice", "owner", "pi-1", "pd-1", TaskStatus.ASSIGNED, now, now, now, 75, mapOf("k" to "v"))
        assertEquals("alice", t.assignee)
        assertEquals("owner", t.owner)
        assertEquals("desc", t.description)
        assertEquals(75, t.priority)
        assertEquals(TaskStatus.CREATED, t.copy(status = TaskStatus.CREATED).status)
        assertNotNull(t.hashCode())
    }

    @Test fun `TaskFilter defaults`() {
        val f = TaskFilter()
        assertNull(f.assignee)
        assertNull(f.candidateGroup)
        assertNull(f.processInstanceId)
        assertNull(f.status)
        assertEquals(50, f.limit)
        assertEquals(0, f.offset)
    }

    @Test fun `TaskFilter with all params`() {
        val f = TaskFilter("alice", "managers", "pi-1", TaskStatus.ASSIGNED, 25, 10)
        assertEquals("alice", f.assignee)
        assertEquals("managers", f.candidateGroup)
        assertEquals(25, f.limit)
        assertEquals(10, f.offset)
    }

    @Test fun `EngineInstanceStatus fields`() {
        val s = EngineInstanceStatus("i-1", "wk", "bk", EngineInstanceStatus.Status.RUNNING, now, null, mapOf("x" to 1), "act-1", "ei-1")
        assertEquals("i-1", s.instanceId)
        assertEquals("wk", s.workflowKey)
        assertEquals("bk", s.businessKey)
        assertEquals("act-1", s.currentActivityId)
        assertEquals("ei-1", s.engineInstanceId)
        assertNotNull(s.toString())
    }

    @Test fun `HistoricInstanceInfo fields`() {
        val h = HistoricInstanceInfo("i-1", "pd-1", "bk", now, now, 5000L, "completed", mapOf("x" to 1))
        assertEquals("i-1", h.instanceId)
        assertEquals("pd-1", h.processDefinitionId)
        assertEquals(5000L, h.durationInMillis)
        assertEquals("completed", h.deleteReason)
        assertNotNull(h.variables)
        assertNotNull(h.toString())
    }

    @Test fun `Incident fields`() {
        val inc = Incident("inc-1", "pi-1", "exec-1", "act-1", IncidentType.FAILED_JOB, "msg", "cause", now, true)
        assertEquals("inc-1", inc.id)
        assertEquals("pi-1", inc.processInstanceId)
        assertEquals("exec-1", inc.executionId)
        assertEquals("act-1", inc.activityId)
        assertEquals(IncidentType.FAILED_JOB, inc.type)
        assertTrue(inc.resolved)
        assertNotNull(inc.toString())
    }

    @Test fun `AdapterCapabilities copy`() {
        val c = AdapterCapabilities.createBpmnCapabilities()
        val withDmn = c.copy(supportsDMN = true)
        assertTrue(withDmn.supportsDMN)
        assertTrue(withDmn.supportsUserTasks)
        assertNotNull(c.hashCode())
    }
}
